version: '3.7'

services:
  app:
    image: registration-frontend:latest
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: registration-frontend
    network_mode: bridge
    ports:
      - ${PROJECT_PORT}:80
    restart: always
    env_file: .env